GET http://localhost:8080/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlMzcxM2RmNzJjZGZlM2QzY2VjM2UwYyIsIm5hbWUiOiJ0YW1yYXQiLCJlbWFpbCI6InRhbXJhdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRvd04uNW9kaUs4Q2l5cFoyelYyMFJlM214bDFUN1BtRFp6OXphWjZVdFJ0WkVGbnFCVVZ6eSIsImRhdGUiOiIyMDIwLTAyLTAyVDE4OjI0OjMxLjk4MVoiLCJfX3YiOjB9LCJpYXQiOjE1ODA2NzE5NjAsImV4cCI6MTU4MDc0Mzk2MH0.rM4k9dXyFPqEFVhTOrgYpG8heRQWddADsEnuuzfsMYU
###
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email":"tamrat@gmail.com","password":"123456"
}

### 
POST http://localhost:8080/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlMzcxM2RmNzJjZGZlM2QzY2VjM2UwYyIsIm5hbWUiOiJ0YW1yYXQiLCJlbWFpbCI6InRhbXJhdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRvd04uNW9kaUs4Q2l5cFoyelYyMFJlM214bDFUN1BtRFp6OXphWjZVdFJ0WkVGbnFCVVZ6eSIsImRhdGUiOiIyMDIwLTAyLTAyVDE4OjI0OjMxLjk4MVoiLCJfX3YiOjB9LCJpYXQiOjE1ODA3MjQ2MzAsImV4cCI6MTU4MDc5NjYzMH0.lg5XP0RpfX5VfAdbc9meNGMsL_NEsGtCgdn7gpS3oLQ

{
"name":"Facebook",
 "subject":"Whatsup", 
 "content": "Pending",
  "email":"tamrat@gmail.com"
}

###
PUT http://localhost:8080/posts/5e37153bc1260a205ca37a25
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlMzcxM2RmNzJjZGZlM2QzY2VjM2UwYyIsIm5hbWUiOiJ0YW1yYXQiLCJlbWFpbCI6InRhbXJhdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRvd04uNW9kaUs4Q2l5cFoyelYyMFJlM214bDFUN1BtRFp6OXphWjZVdFJ0WkVGbnFCVVZ6eSIsImRhdGUiOiIyMDIwLTAyLTAyVDE4OjI0OjMxLjk4MVoiLCJfX3YiOjB9LCJpYXQiOjE1ODA2NzI2ODcsImV4cCI6MTU4MDc0NDY4N30.z1Qmu5l32ceaDIdFqKqA4zyPE_lLlfxjFp6liUS8At8

{
"name":"tamrat",
 "subject":"Asa", 
 "content": "A B C D",
 "email":"tamrat@gmail.com"
}
###
DELETE http://localhost:8080/post/5e37149ae5e4624dd0ec4ce9
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlMzcxM2RmNzJjZGZlM2QzY2VjM2UwYyIsIm5hbWUiOiJ0YW1yYXQiLCJlbWFpbCI6InRhbXJhdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRvd04uNW9kaUs4Q2l5cFoyelYyMFJlM214bDFUN1BtRFp6OXphWjZVdFJ0WkVGbnFCVVZ6eSIsImRhdGUiOiIyMDIwLTAyLTAyVDE4OjI0OjMxLjk4MVoiLCJfX3YiOjB9LCJpYXQiOjE1ODA2NzI2ODcsImV4cCI6MTU4MDc0NDY4N30.z1Qmu5l32ceaDIdFqKqA4zyPE_lLlfxjFp6liUS8At8

